#:schema node_modules/wrangler/config-schema.json
name = "wabac-cors-proxy"
main = "./index.ts"
compatibility_date = "2024-08-06"
workers_dev = true
compatibility_flags = ["nodejs_compat_v2"]
placement = { mode = "smart" }
